services:

  api:
    build: ./backend
    volumes: 
      - logs:/app/logs


  client:
    build: ./frontend
    depends_on: 
      - api

    ports:
      - "3000:3000"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: sabir
      MONGO_INITDB_ROOT_PASSWORD: sabir123
      MONGO_INITDB_DATABASE: appdb


volumes: 
  logs: